name: ci
on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/ci.yml'
      - '*.h'
      - '*.c'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/ci.yml'
      - '*.h'
      - '*.c'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build-test
      run: |
        gcc main.c -o ruapu
        ./ruapu
    - name: build-test-clang
      run: |
        clang main.c -o ruapu-clang
        ./ruapu-clang

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build-test
      run: |
        clang main.c -o ruapu
        ./ruapu

  macos-arm64:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: build-test
      run: |
        clang main.c -o ruapu
        ./ruapu

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: build-test
      run: |
        cl.exe /Fe: ruapu.exe main.c
        .\ruapu.exe
    - name: build-test-mingw
      shell: bash
      run: |
        gcc main.c -o ruapu-mingw.exe
        ./ruapu-mingw.exe
